use std::env;
use std::fs;

use heck::ToSnakeCase;
use itertools::Itertools;
use syn::{GenericArgument, Item, ItemEnum, ItemStruct, PathArguments, Type};

#[derive(Debug, Clone)]
enum FieldType {
  Bool,
  I8,
  U8,
  I16,
  U16,
  I32,
  U32,
  I64,
  U64,
  F32,
  F64,
  QString,
  Vec(Box<FieldType>),
  Optional(Box<FieldType>),
  Custom(String),
}

fn main() {
  let args: Vec<String> = env::args().collect();
  if args.len() < 2 {
    eprintln!("Usage: rust_qt_codegen <input.rs>");
    std::process::exit(1);
  }

  let src = fs::read_to_string(&args[1]).expect("failed to read input file");
  let file = syn::parse_file(&src).expect("failed to parse rust file");

  println!(
    r#"#pragma once

/**
 * Auto-generated by qt_codegen. Do not edit by hand.
 */

#include <QByteArray>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QJsonValue>
#include <QMap>
#include <QString>
#include <QVariant>
#include <QVector>
#include "./optional.h"

template <typename T>
QVector<T> buildVector(QJsonValue arrayValue, T (*func)(QJsonValue)) {{
  const QJsonArray array = arrayValue.toArray();
  QVector<T> vector;
  vector.reserve(array.size());
  for (const QJsonValue &value : array) {{
    vector.append(func(value));
  }}

  return vector;
}}
"#,
  );

  file.items.iter().for_each(|item| {
    if let Item::Struct(s) = item {
      gen_struct_class(s)
    }
  });

  file.items.iter().for_each(|item| {
    if let Item::Enum(e) = item {
      gen_enum_class(e)
    }
  });
}

fn map_type(ty: &Type) -> FieldType {
  if let Type::Path(type_path) = ty {
    let segment = type_path.path.segments.last().expect("empty type path");
    match segment.ident.to_string().as_str() {
      "bool" => FieldType::Bool,
      "i8" => FieldType::I8,
      "u8" => FieldType::U8,
      "i16" => FieldType::I16,
      "u16" => FieldType::U16,
      "i32" => FieldType::I32,
      "u32" => FieldType::U32,
      "i64" | "isize" => FieldType::I64,
      "u64" | "usize" => FieldType::U64,
      "f32" => FieldType::F32,
      "f64" => FieldType::F64,
      "String" | "str" | "Timestamp" => FieldType::QString,
      "Vec" => FieldType::Vec(Box::new(map_type(
        get_generic(segment).expect("Vec<T> needs a type param"),
      ))),
      "Option" => FieldType::Optional(Box::new(map_type(
        get_generic(segment).expect("Option<T> needs a type param"),
      ))),
      other => FieldType::Custom(other.to_string()),
    }
  } else {
    panic!("unsupported field type: {:?}", ty);
  }
}

fn get_generic(segment: &syn::PathSegment) -> Option<&Type> {
  if let PathArguments::AngleBracketed(args) = &segment.arguments {
    for arg in &args.args {
      if let GenericArgument::Type(t) = arg {
        return Some(t);
      }
    }
  }
  None
}

fn cpp_type(ty: &FieldType) -> String {
  match ty {
    FieldType::Bool => "bool".into(),
    FieldType::I8 => "qint8".into(),
    FieldType::U8 => "quint8".into(),
    FieldType::I16 => "qint16".into(),
    FieldType::U16 => "quint16".into(),
    FieldType::I32 => "qint32".into(),
    FieldType::U32 => "quint32".into(),
    FieldType::I64 => "qint64".into(),
    FieldType::U64 => "quint64".into(),
    FieldType::F32 => "float".into(),
    FieldType::F64 => "double".into(),
    FieldType::QString => "QString".into(),
    FieldType::Vec(inner) => format!("QVector<{}>", cpp_type(inner)),
    FieldType::Optional(inner) => format!("Optional<{}>", cpp_type(inner)),
    FieldType::Custom(name) => name.clone(),
  }
}

fn gen_read(ty: &FieldType, value: &str) -> String {
  match ty {
    FieldType::Bool => format!("{value}.toBool();"),
    FieldType::I8 | FieldType::I16 | FieldType::I32 => {
      format!("static_cast<{cty}>({value}.toInt());", cty = cpp_type(ty))
    }
    FieldType::U8 | FieldType::U16 | FieldType::U32 => {
      format!("static_cast<{cty}>({value}.toVariant().toUInt());", cty = cpp_type(ty))
    }
    FieldType::I64 => format!("{value}.toVariant().toLongLong();"),
    FieldType::U64 => format!("{value}.toVariant().toULongLong();"),
    FieldType::F32 => format!("static_cast<float>({value}.toDouble());"),
    FieldType::F64 => format!("{value}.toDouble();"),
    FieldType::QString => format!("{value}.toString();"),
    FieldType::Custom(name) => format!("{name}::fromJson({value}.toObject());"),
    FieldType::Vec(inner) => {
      let ety = cpp_type(inner);
      let read = &gen_read(inner, "value");
      format!("buildVector<{ety}>({value}, [](QJsonValue value) {{ return {read} }});")
    }
    FieldType::Optional(inner) => gen_read(inner, value),
  }
}

fn gen_struct_class(s: &ItemStruct) {
  struct FieldInfo {
    name: String,
    ty: FieldType,
  }

  let name = s.ident.to_string();

  let fields = s
    .fields
    .iter()
    .map(|f| FieldInfo {
      name: f.ident.as_ref().unwrap().to_string(),
      ty: map_type(&f.ty),
    })
    .collect::<Vec<_>>();

  let field_decls = fields
    .iter()
    .map(|f| {
      let name = &f.name;
      let ty = cpp_type(&f.ty);
      format!("{ty} {name} = {{}};")
    })
    .join("\n  ");

  let field_reads = fields
    .iter()
    .map(|f| {
      let name = &f.name;
      let read = gen_read(&f.ty, &format!("jsonObj.value(\"{name}\")"));

      if let FieldType::Optional(_) = &f.ty {
        format!("if (jsonObj.contains(\"{name}\") && !jsonObj.value(\"{name}\").isNull()) {{ result.{name} = {read} }}")
      } else {
        format!("result.{name} = {read}")
      }
    })
    .join("\n");

  println!(
    r#"
class {name} {{
public:
  {field_decls}

  static {name} fromJson(const QJsonObject &jsonObj) {{
    {name} result;
    {field_reads}
    return result;
  }}
}};
"#
  );
}

fn gen_enum_class(e: &ItemEnum) {
  struct VariantInfo {
    name: String,
    field: String,
    ty: String,
  }

  let name = e.ident.to_string();

  let variants = e
    .variants
    .iter()
    .flat_map(|v| {
      let variant_name = v.ident.to_string();
      let field_name = variant_name.to_snake_case();

      let field = if let syn::Fields::Unnamed(fields) = &v.fields
        && fields.unnamed.len() == 1
      {
        fields.unnamed.first()?
      } else {
        eprintln!("warning: skipping enum {name}: variant {variant_name} is not a newtype variant");
        return None;
      };

      let inner_type = if let FieldType::Custom(ty_name) = map_type(&field.ty) {
        ty_name
      } else {
        eprintln!("warning: skipping enum {name}: variant {variant_name} does not contain a custom struct type");
        return None;
      };

      Some(VariantInfo {
        name: variant_name,
        field: field_name,
        ty: inner_type,
      })
    })
    .collect::<Vec<_>>();

  if variants.is_empty() {
    return;
  }

  let kind_list = variants.iter().map(|v| v.name.clone()).join(",");

  let field_decls = variants
    .iter()
    .map(|v| format!("Optional<{}> {} = {{}};", v.ty, v.field))
    .join("\n");

  let field_reads = variants
    .iter()
    .map(|v| {
      let name = &v.name;
      let field = &v.field;
      let ty = &v.ty;
      format!(
        r#"
if (kind == "{name}") {{
  result.kind = Kind::{name};
  result.{field} = {ty}::fromJson(jsonObj);
  return result;
}}"#
      )
    })
    .join(" else ");

  let helpers = variants
    .iter()
    .map(|v| {
      let name = &v.name;
      format!("bool is{name}() const {{ return kind == Kind::{name}; }}")
    })
    .join("\n");

  println!(
    r#"
class {name} {{
public:
  enum class Kind {{
    Unknown,
    {kind_list}
  }};

  Kind kind = Kind::Unknown;
  {field_decls}

  static {name} fromJson(const QJsonObject &jsonObj) {{
    {name} result;
    const QString kind = jsonObj.value("kind").toString();

    {field_reads}

    return result;
  }}

  bool isValid() const {{ return kind != Kind::Unknown; }}
  {helpers}
}};
"#
  );
}
