; Your Hardcover.app API key or OAuth access token.
; access_token =

; Whether auto-sync is enabled or disabled by default for each book.
auto_sync_default = false

; What privacy setting to use when creating new journal entries.
; - account   Use the privacy setting specified in your Hardcover.app account
; - public    The journal entries will be visible to anyone.
; - follows   The journal entries will be visible only to people you follow.
; - private   Only you can see your journal entries.
journal_privacy = account

; If sync fails due to lack of internet connection, automatically retry next
; time you connect to WiFi.
retry_on_network = true

; Whether to sync Kobo annotations (highlights and notes) to the Hardcover.app
; journal.
sync_annotations = true

; Run auto-sync when a book is closed (including putting the Kobo to sleep) if
; the difference between the last synced read percentage and the current read
; percentage is greater than this threshold (in percentage points).
; Set to -1 to disable.
sync_on_close = 1

; Run auto-sync while reading when the difference between the last synced read
; percentage and the current read percentage is greater than this number (in
; percentage points).
; Set to -1 to disable.
sync_on_read = 20

; Run auto-sync at the specified hour even if the Kobo is asleep. Possible
; values are 0-23 where 0 is midnight, 1 is 1am, 22 is 10pm, etc.
; Set to -1 to disable.
sync_on_schedule = -1
